export default {
  submitConfigs: `submitConfigs`,
  searchTemplate: `searchTemplate`,
  getTemplateList: `getTemplateList`,
  outputFiles: `outputFiles`,
  addTemplateInfo: `addTemplateInfo`,
  deleteTemplate: `deleteTemplate`,
  saveTemplateInfos: `saveTemplateInfos`,
  addComponent: `addComponent`,
  copyComponent: `copyComponent`,
  onLayoutSortChange: `onLayoutSortChange`,
  clearSelectedStatus: `clearSelectedStatus`,
  selectComponent: `selectComponent`,
  clearChildNodes: `clearChildNodes`,
  deleteComponent: `deleteComponent`,
  changeStyles: `changeStyles`,
  resizeChange: 'resizeChange',
  changeProps: `changeProps`,
  overTarget: `overTarget`,
  clearHovered: `clearHovered`,
  undo: `undo`,
  redo: `redo`,
  getDragSource: `getDragSource`,
  getDropTarget: `getDropTarget`,
  changePlatform: `changePlatform`,
  resetProps: 'resetProps',
  resetStyles: 'resetStyles',
  clearDropTarget: 'clearDropTarget',
  clearDragSource: 'clearDragSource',
  removeState: 'removeState',
  setApi: 'setApi',
  setComponentState: 'setComponentState',
  setStateDomain: 'setStateDomain',
  restStateDomain: 'restStateDomain',
  initPageBrickdState: 'initPageBrickdState',
  removePageBrickdState: 'removePageBrickdState',
  dragSort:'dragSort'
};
