export default {
  submitConfigs: `submitConfigs`,
  searchTemplate: `searchTemplate`,
  getTemplateList: `getTemplateList`,
  outputFiles: `outputFiles`,
  addTemplateInfo: `addTemplateInfo`,
  deleteTemplate: `deleteTemplate`,
  saveTemplateInfos: `saveTemplateInfos`,
  addComponent: `addComponent`,
  copyComponent: `copyComponent`,
  onLayoutSortChange: `onLayoutSortChange`,
  clearSelectedStatus: `clearSelectedStatus`,
  selectComponent: `selectComponent`,
  clearChildNodes: `clearChildNodes`,
  deleteComponent: `deleteComponent`,
  changeStyles: `changeStyles`,
  changeVisualizedStyles: 'changeVisualizedStyles',
  changeProps: `changeProps`,
  undo: `undo`,
  redo: `redo`,
  changePlatform: `changePlatform`,
  resetProps: 'resetProps',
  initPageBrickdState: 'initPageBrickdState',
  createLayers: 'createLayers',
  deleteLayers: 'deleteLayers',
  copyLayers: 'copyLayers',
  renameLayers: 'renameLayers',
  changeLayer: 'changeLayer',
  changeSeniorProps:'changeSeniorProps',
};
